[project]
name = "redaffair"
version = "1.222.2"
description = "Red Affair game"
requires-python = ">=3.10"
dependencies = [
    "kivy",
    "charset_normalizer==2.1.1"
]

[tool.kivy-school]
package = "ws.tilda.sentryprotocol.redaffair"
entry_point = "main.py"
version_code = 12222

[tool.kivy-school.android]
package_name = "ws.tilda.sentryprotocol.redaffair"
archs = ["arm64-v8a"]